### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#247]
# Hooray!

This issue is complete, it will be closed once the final PR, #400 is merged.

---

As we remove jQuery and SUI JS from these components, we're also updating their legacy component APIs to our v1 API.  You can see more of that work in #269.

The [CONTRIBUTING.md](https://github.com/TechnologyAdvice/stardust/blob/master/CONTRIBUTING.md) guide details how to go about designing a component API.  The [Spec out the API](https://github.com/TechnologyAdvice/stardust/blob/master/CONTRIBUTING.md#spec-out-the-api) section is of primary importance.

You can reference the Dropdown for a complex jQuery free stateful component.  You can reference the Progress (#324) or Accordion for more simple jQuery free stateful components.
## PRs
- [x] ~~#220 doc site and _meta updates~~
- [x] ~~#221 List item prop renderers~~
- [x] ~~#222 component utils~~
- [x] ~~#223 Common tests~~
- [x] ~~#224 AutoControlledComponent~~
- [x] ~~#226 Dropdown without jQuery~~
- [x] ~~#225 Select component~~
- [x] ~~#260 Checkbox without jQuery~~
- [x] ~~#400 Form without jQuery~~
- [x] ~~#344 Message without jQuery~~
- [x] ~~#324 Progress without jQuery~~
- [x] ~~#400 Remove traces of jQuery~~
  - [x] ~~webpack config~~
  - [x] ~~karma config~~
  - [x] ~~_default config vendors~~
  - [x] ~~package dependencies~~
  - [x] l~~ib/jquery~~
## ~~TODOs~~

Follow up issues that sprung from the above PRs:
- [x] ~~#229 [remove babel-polyfil](https://github.com/TechnologyAdvice/stardust/pull/206/files#r61193441)~~
- [x] ~~#231 [remove keyboard event polyfill in favor of util](https://github.com/TechnologyAdvice/stardust/pull/226#discussion_r61350959)~~
- [x] ~~#??? [functional domEvent methods](https://github.com/TechnologyAdvice/stardust/pull/222/files#r61273736)~~ deeming this not necessary until we get other major priorities done
- [x] ~~#232 [use `process.env.NODE_ENV` instead of `__PROD__`](https://github.com/TechnologyAdvice/stardust/pull/224/files#r61321467)~~
- [x] ~~#??? [event util](https://github.com/TechnologyAdvice/stardust/pull/226)~~ see #284 instead
- [x] ~~#233 [logging util](https://github.com/TechnologyAdvice/stardust/pull/226)~~
- [x] ~~#250 [consumer prop spreading util](https://github.com/TechnologyAdvice/stardust/pull/226)~~

---

> This issue was previously PR #206.  It has been moved here since that PR was merged. This is the checklist for the remaining PRs and Todos.
