### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#2747]
React 16 offers some updates that we should implement, however, we'll need to drop support for React 15 when doing so.  Let's batch these changes into an upcoming major release:

- [x] #2746 Portal to use `ReactDOM.createPortal` (https://reactjs.org/docs/portals.html)
- [ ] Refactor and simplify Accordion to return an array of panels (https://reactjs.org/docs/react-component.html#render)
- [ ] Refactor and simplify Breadcrumb to return an array of sections/dividers (https://reactjs.org/docs/react-component.html#render)
- [ ] #2306 Fix ref issues using `forwardRef` (https://reactjs.org/docs/forwarding-refs.html)
- [x] #2842 Use `PureComponent` for `Icon` and `Flag`

@Semantic-Org/react-maintainers feel free to add to this list at will...

**Comment by layershifter** [comment]
Added `Breadcrumb` to list, there is quite [unfriendly](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.79.1/src/collections/Breadcrumb/Breadcrumb.js#L43) code.

**Comment by packetstracer** [comment]
Maybe you should add a Fix for unsafe lifecycle methods for asynchronous rendering. 

In the project I'm working currently, since we activated the new React's Strict Mode, we are getting a lot of console warnings about using unsafe lifecycle methods y some of the components. 

For example:

`componentWillMount: Please update the following components to use componentDidMount instead: Dropdown`

`componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Dropdown, Menu, Tab`

`componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: AccordionAccordion`

`componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Checkbox`

**Comment by layershifter** [comment]
@packetstracer see #2732, feel free to contribute 👍
