### ISSUE TITLE
v3: roadmap to release

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#4409]
This PR tracks work for Semantic UI React v3 🎉 

## Pre beta-0 ✅ 

- [x] chore: replace `ta-scripts` with `release-it`

## For beta-0 ✅ 

- [x] All components support native [ref forwarding](https://reactjs.org/docs/forwarding-refs.html) #4233
- [x] **BREAKING CHANGE** remove `Ref` component #4286
- [x] **BREAKING CHANGE** remove `Visibility` component #4257
- [x] **BREAKING CHANGE** `Input`, `Button` & `TextArea` are forwarding refs to native elements
- [x] **BREAKING CHANGE** `Transition` static props #4266

## Post beta-0 ✅ 

- [x] Document breaking changes #4431

## For beta-2 ✅ 

- [x] fix: remove usages of `.defaultProps` #4426, see https://github.com/Semantic-Org/Semantic-UI-React/issues/4426#issuecomment-1627680271
- [x] chore: update typings, ensure that they support `ref` forwarding #4432, see https://github.com/Semantic-Org/Semantic-UI-React/issues/4432#issuecomment-1627741193
- [x] #4433

## For beta-3

- [x] #4457
- [x] #4490 
- [ ] **BREAKING CHANGE** Event handling: remove `eventStack`
- [ ] test: `validateTrigger` should handle `forwardRef`
- [ ] chore: remove `.displayName` in production
- [ ] docs: update contributing guide
- [ ] docs: update Github templates
- [ ] docs: update introduction to remove AutoControlledComponent mentions
- [ ] docs: rename classname generators (currently they violate rules of hooks as their names start with `use`)
- [x] chore: enable ESLint plugin for rules of hooks #4498

## For RC

- [ ] chore: integrate monosize
- [ ] chore: add bundle size fixtures for all components
- [ ] chore: remove dependency on lodash
- [ ] chore: deprecate "dot-syntax"
  - [ ] add warnings
  - [ ] add a codemod

## After release
- [ ] docs: update CodeSandbox templates

**Comment by vinodhrajamuralidharan** [comment]
@layershifter what is the status user.React.forwardRef PR status? I see it is still in open

**Comment by layershifter** [comment]
@vinodhrajamuralidharan I had a conversation with @levithomason about that PR. The agreement was that he will review it and then we can proceed. I am also waiting for that PR to be merged 😉

**Comment by sunech** [comment]
Is there any ETA on v3 progress @levithomason / @layershifter ?
There was such a great traction in December, so I started to get my hopes up for SUIR again 🤞 Would hate to see it stall again, with all the great work that has been put in to it 🙏

**Comment by layershifter** [comment]
[`3.0.0-beta.0`](https://www.npmjs.com/package/semantic-ui-react/v/3.0.0-beta.0) is out 🎉  Please try and report issues 🙏

**Comment by DreierF** [comment]
Thanks a lot @layershifter for the effort!
I didn't run into any issues yet with the beta besides the probably expected Typescript issues such as https://stackblitz.com/edit/react-ts-ejdyij?file=App.tsx.

**Comment by sunech** [comment]
Is there anything further that we can help test, in order to proceed with the v3 release?

**Comment by tourman** [comment]
@layershifter could you please update the status? FYI @levithomason 
1. Is the roadmap todo list still relevant? If not, please refresh or update it. In particular, please add the links to the appropriate PRs, branches, etc.
2. Please add more clear description for each point. E.g. what is `Document breaking changes` that is not checked?
3. If you are not about to move on with the project, please initiate a process to pass it to the community. There are projects and people who are waiting for the new version trying to replace SUIR with a fork or something else.

**Comment by layershifter** [comment]
@tourman 

1/2. Yes, it's relevant. I will update it to be more precise and detailed 👍 
3. To be clear, I don't have time and motivation to maintain this project currently. If there people who are interested in move forward it would be great to hear back 🐱

**Comment by sunech** [comment]
@layershifter thank you for all you great work so far, highly appreciate your effort!

This project is too good to just die, so I really hope someone wants to pick up from here.
Would love to support if I can, not experienced enough to contribute with code though.
If any freelancers are considering, I would gladly pay for some of your time to get the ball rolling on this again.

**Comment by layershifter** [comment]
> Thanks a lot @layershifter for the effort! I didn't run into any issues yet with the beta besides the probably expected Typescript issues such as https://stackblitz.com/edit/react-ts-ejdyij?file=App.tsx.

@DreierF it's indeed a bug, see #4432 for details.

> Is there anything further that we can help test, in order to proceed with the v3 release?

@sunech @tourman I updated changelog and created migration guide (https://react.semantic-ui.com/migration-guide). I also updated issues that needs to be solved to release the next beta. Both issues contain action items and examples of changes needed to be done.

Help on these issues is much appreciated 🐱

**Comment by siarheipashkevich** [comment]
@layershifter thanks for your work on this package, do you have approximate time when you plan to release 3.0 version?

**Comment by layershifter** [comment]
[`3.0.0-beta.2`](https://www.npmjs.com/package/semantic-ui-react/v/3.0.0-beta.2) is out 🎉 

It fixes `.defaultProps` warnings, TypeScript typings & issues with `appDir` in Next.js.

Please try and report issues 🙏

**Comment by fniessink** [comment]
I can report that after making [a few small changes](https://github.com/ICTU/quality-time/pull/7457/files) all frontend unit tests of [Quality-time](https://github.com/ICTU/quality-time) pass with 3.0.0-beta.2:

```console
Test Suites: 85 passed, 85 total
Tests:       694 passed, 694 total
Snapshots:   0 total
Time:        67.751 s, estimated 70 s
```

Most changes were needed because popups would not appear at the right position with 3.0.0-beta.2. Adding a span or div around triggers solved this. I can't reproduce this issue on the [Semantic UI React documentation site](https://react.semantic-ui.com/modules/popup/) so I guess it's an issue on our side.

**Comment by dominikdosoudil** [comment]
I don't think that it's worth creating a issue but the Sticky component didn't work after the upgrade. I needed to add `scrollContext` because there is a scrollable div instead of whole window. I am not sure if it's somehow breaking change or I had it wrong even before. I am just mentioning as a possible information to migration guide.

**Comment by Noahkoole** [comment]
> I can report that after making [a few small changes](https://github.com/ICTU/quality-time/pull/7457/files) all frontend unit tests of [Quality-time](https://github.com/ICTU/quality-time) pass with 3.0.0-beta.2:
> 
> ```
> Test Suites: 85 passed, 85 total
> Tests:       694 passed, 694 total
> Snapshots:   0 total
> Time:        67.751 s, estimated 70 s
> ```
> 
> Most changes were needed because popups would not appear at the right position with 3.0.0-beta.2. Adding a span or div around triggers solved this. I can't reproduce this issue on the [Semantic UI React documentation site](https://react.semantic-ui.com/modules/popup/) so I guess it's an issue on our side.

This seems to also be an issue on our side. Started with the transition to beta.2 and adding a span around it indeed fixed it

**Comment by atti187** [comment]
@layershifter - I fixed the first task in the beta-3 release. Could you please add issues for the rest of tasks in the list and I'll see if I can have a go at some of them? Would be nice to get v3 out!

**Comment by BlenesiAron** [comment]
When is the v3 release scheduled for?

**Comment by triemstr** [comment]
> When is the v3 release scheduled for?

Outside of the eventStack breaking change, it looks like it is just a lot of testing and documentation for the 3.0.0 beta 3 release. I'm not sure if @layershifter is taking pull requests, but maybe some in the community can assist.

**Comment by layershifter** [comment]
> I'm not sure if @layershifter is taking pull requests, but maybe some in the community can assist.

Yep, if somebody is brave enough to get rid of `EventStack`, I would be happy to review the changes.

**Comment by triemstr** [comment]
@layershifter Would you consider just going with the current state as version 3 and then working on the rest as version 4?

Only reason is that so many people are getting the `props` and other javascript warnings now and they don't know that the version 3 beta solves them. Running `outdated` on npm sources wouldn't show the version 3 beta. Might be a good way to keep the upgrades occurring so that a few more community members may jump in on `EventStack`.

Just a thought, unless someone is about there on EventStack.

**Comment by dominikdosoudil** [comment]
@triemstr I am up to looking into the EventStack however there might be one more thing blocking the release that needs to be fixed: https://github.com/Semantic-Org/Semantic-UI-React/pull/4233/files#r1837715017

**Comment by dominikdosoudil** [comment]
@layershifter So few past days, I've been looking into the EventStack in the Modal (and source code of the event-stack) and there is the thing "eventPool". As I think that I understand that it might help keeping multiple references to same callback (I imagine some independent unsubscribing), I can't really see the real purpose of it (or what and if something would break after removing it). 

Could you possibly give me some hint or direction or use case where it's necessary?

**Comment by layershifter** [comment]
@dominikdosoudil My previous attempt there #3734 (ignore it, just to provide a perspective). The `EventStack` pattern is so fundamentally broken that it’s not even worth explaining what it does 💩. The `eventPool` prop should definitely be removed.  

Let me break down the complexity behind this issue. The [`.contains()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) method is used to determine whether to close a `Modal` (for example) on an inside or outside click. This works well in straightforward cases like the following (e.g., clicking a button):  

```jsx
// JSX
<Modal>
  <Button />
</Modal>

// HTML
<body>
  <div class="ui modal">
    <button class="ui button"></button>
  </div>
</body>
```  

However, it fails in nested scenarios. For example:  

```jsx
// JSX
<Modal>
  <Popup>
    <Button />
  </Popup>
</Modal>

// HTML
<body>
  <div class="ui modal">
  </div>
  <div class="ui popup">
    <button class="ui button"></button>
  </div>
</body>
```  

In this case, the `ui popup` is not a child of `ui modal`, causing `.contains()` to break. A more detailed explanation of this issue can be found here: [Virtual Parents](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-portal/library/README.md#virtual-parents).  

To address this, I propose the following steps:  
1. Add a test case for this scenario (refer to `cypress/integration/Sidebar/Sidebar.spec.js` as an example).  
2. Implement the virtual parent approach, as seen in this PR: [microsoft/fluentui#18148](https://github.com/microsoft/fluentui/pull/18148), and the related code: https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-utilities/src/virtualParent).  

Hope this helps.

**Comment by dominikdosoudil** [comment]
@layershifter I see, the nesting is tricky. Converted #4504 to draft. I am gonna look into it and decide if i am "brave enough" after all. 😆

Thank you for explaining it.

**Comment by dominikdosoudil** [comment]
I've explored the links you sent me and I must say that the prop injecting into element object seems pretty hacky to me. However it actually seems to be the most straightforward solution. I think that I might start working on porting that mechanism into SUIR about next week or so.

**Comment by layershifter** [comment]
> I've explored the links you sent me and I must say that the prop injecting into element object seems pretty hacky to me. However it actually seems to be the most straightforward solution. I think that I might start working on porting that mechanism into SUIR about next week or so.

@dominikdosoudil sounds great ❤️ FYI I explored other solutions (with React Context), however that one in Fluent worked so far the best and is the most straightforward. But in general, I agree with you 🐱

**Comment by BastianW13** [comment]
Hey at all,

just wanted to ask if there is an ETA on the release candidate. We've been working with SUI and SUIR and are really happy with it. The issues that are already fixed in the current beta are from what i can tell already sufficient for us. However, using a beta version gives some issues with npm and we would prefer not using a beta versions in general. Since it will be some time until we go live with our project (probably in early autumn), we currently try to decide if we should already switch to v3 and hope for an official release of SUIR v3, or just live with some kinks of v2.
Any thoughts on how long it could be until the release?

**Comment by sunech** [comment]
If anyone doing freelance work has the time, skill and passion to bring this wonderful project back on track, please reach out.
Not sure how much work is required, but I would be happy to compensate for some work to get proper React 19 compatibility and a stable v3 released. Maybe there are other commercial users as well, who would be interested in contributing?

**Comment by dominikdosoudil** [comment]
@BastianW13, @sunech  I started working on removing EventStack as @layershifter wants it removed in v3 however I am currently fully occupied by some large project in the company I am working for so I had to postpone SUIR. However as v3 would also help the company as well, I am still planing to get back to it. However right now, I guess that it will take few more months at least.

If you wanna help, we've discussed the topic here in the roadmap and also in #4504. At least some ideas/opinions would be really appreciated by me.

**Comment by sunech** [comment]
Great to hear @dominikdosoudil ! I had a look, but unfortunately it goes beyond my knowledge/experience.

**Comment by LeeBoonKong** [comment]
Is this project abandoned?

**Comment by heath-freenome** [comment]
> Is this project abandoned?

@dominikdosoudil  or @layershifter can you confirm or deny that this project is dead?

**Comment by dominikdosoudil** [comment]
@LeeBoonKong, @heath-freenome I am not a maintainer so I can't say much however my feeling about it is that the project is not actively developed but maintainers are still there and able to accept PRs.

My company is using SUIR in the core project so we are willing to invest some time to development of it however since we are really small to the number of FE developers, we can't do much impact in a short time and more priority stuff usually interrupts it when I try to do something.

Although SUI is really great when it comes to the design, I would say that it's risky picking it because it might result in future compatibility issues with future versions of react etc.

**Comment by LeeBoonKong** [comment]
@dominikdosoudil Thanks for the clarification, the previous developers of my project picked SUIR as well and I am a bit worried on the future of this framework, as React version moving forward, SUIR v3 that supposed to support React 19 is still in beta for more than a year now.

**Comment by triemstr** [comment]
> [@dominikdosoudil](https://github.com/dominikdosoudil) Thanks for the clarification, the previous developers of my project picked SUIR as well and I am a bit worried on the future of this framework, as React version moving forward, SUIR v3 that supposed to support React 19 is still in beta for more than a year now.

Is https://github.com/fomantic/Fomantic-UI an option? It is a semantic community fork. Of course many others out there.

**Comment by dominikdosoudil** [comment]
@triemstr IIRC I've tried fomantic once however it was not compatible as drop-in replacement so I didn't use it in the end. Doesn't mean that it's not worth making the effort migrating tho, I can't really say.
