### ISSUE TITLE
Release: Roadmap

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#657]
Hi, guys!

I think that we're ready to form roadmap for 1.0 release, we can keep this issue as global TODO :ship: 

---

There is bunch of refactors that we need to do:
- [ ] #599 Fix prop warnings in tests and docs;
- [ ] #607 Improve performance with update to class-based components;
- [ ] #564 Update docs to latest pattern;
- [ ] #623 Update callbacks for passing props;
- [ ] #524 Remove propTypes in production builds, allow small builds;

---

Add missing components:
- [ ] #185 Advertisement
- [ ] #447 Dimmer
- [ ] #191 Embed
- [ ] #192 Nag
- [ ] #182 Reveal
- [ ] #196 Shape
- [ ] #197 Sidebar
- [ ] #198 Sticky
- [ ] #199 Tab
- [ ] #200 Transition

---

@jcarbo @levithomason Do I miss something?

**Comment by levithomason** [comment]
Heads up, there is already an actual [v1.0 milestone](https://github.com/Semantic-Org/Semantic-UI-React/milestone/1).  Let's use that instead of a checklist.  It is a little easier to manage and has better GitHub integration.

You can add issues like so:

![image](https://cloud.githubusercontent.com/assets/5067638/19279979/9610aca6-8f98-11e6-936f-64c68f81b560.png)
